# Generated by Django 6.0 on 2025-12-15 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='age_group',
            field=models.CharField(choices=[('0-6m', '0-6 Months'), ('6-12m', '6-12 Months'), ('1-2y', '1-2 Years'), ('2-4y', '2-4 Years'), ('4y+', '4+ Years')], default='0-6m', max_length=10),
        ),
    ]
